# Routing is configured per admin in the admin configurations

eavmanager_layout:
    resource: '@CleverAgeEAVManagerLayoutBundle/Resources/config/routing.yml'

sidus_admin:
    resource: .
    type: sidus_admin

eavmanager_admin.wysiwyg.data_selector.media:
    path: /wysiwyg/data-selector/datamedia
    defaults: { _controller: CleverAgeEAVManagerAdminBundle:Wysiwyg:selectMedia }
    options:
        expose: true

eavmanager_admin.wysiwyg.data_selector:
    path: /wysiwyg/data-selector/{configName}
    defaults: { _controller: CleverAgeEAVManagerAdminBundle:Wysiwyg:selectData }
    options:
        expose: true

eavmanager_user:
    resource: '@CleverAgeEAVManagerUserBundle/Resources/config/routing.yml'

eavmanager_asset:
    resource: '@CleverAgeEAVManagerAssetBundle/Resources/config/routing.yml'

sidus_file_upload:
    resource: '@SidusFileUploadBundle/Resources/config/routing.yml'

_liip_imagine:
    resource: '@LiipImagineBundle/Resources/config/routing.xml'

