services:
    CleverAge\EAVManager\ApiPlatformBundle\DataProvider\FamilyDataProvider:
        public: false
        autowire: true
        tags:
            -  { name: api_platform.collection_data_provider, priority: 2 }
            -  { name: api_platform.item_data_provider, priority: 2 }

    CleverAge\EAVManager\ApiPlatformBundle\DataProvider\UserProfileDataProvider:
        public: false
        autowire: true
        tags:
            -  { name: api_platform.item_data_provider, priority: 2 }
