sidus_admin:
    fallback_template_directory: CleverAgeEAVManagerAdminBundle:Base
    configurations:
        media:
            controller: '%eav.controller%'
            entity: '%sidus_data_class%'
            prefix: /medias
            actions:
                list:
                    path:     /{familyCode}/list
                create:
                    path:     /{familyCode}/create
                    form_type: '%eav_form.type%'
                edit:
                    path:     /{familyCode}/{id}/edit
                    form_type: '%eav_form.type%'
                delete:
                    path:     /{familyCode}/{id}/delete
            options:
                hidden: true
                icon: image
                families:
                    Image: ~
                    Document: ~

        media_browser:
            controller: CleverAgeEAVManagerAdminBundle:EAVData # Absolute reference in case it's overriden in the app
            entity: '%sidus_data_class%'
            prefix: /medias_browser
            actions:
                list:
                    path:     /{familyCode}/list
                create:
                    path:     /{familyCode}/create
                    form_type: '%eav_form.type%'
                edit:
                    path:     /{familyCode}/{id}/edit
                    form_type: '%eav_form.type%'
                delete:
                    path:     /{familyCode}/{id}/delete
            options:
                hidden: true
                allow_back: true
                families:
                    Image:
                        datagrid: image_browser
                    Document:
                        datagrid: document_browser

        resource:
            controller: CleverAgeEAVManagerAdminBundle:GenericAdmin
            entity: CleverAge\EAVManager\AssetBundle\Entity\Document
            prefix: /resources
            actions:
                list:
                    path: /
                delete:
                    path: /{id}/delete
            options:
                hidden: true

        user:
            controller: CleverAgeEAVManagerAdminBundle:User
            entity: CleverAge\EAVManager\UserBundle\Entity\User
            prefix: /users
            actions:
                list:
                    path:     /
                create:
                    path:     /create
                    form_type: CleverAge\EAVManager\UserBundle\Form\Type\UserType
                edit:
                    path:     /{id}/edit
                    form_type: CleverAge\EAVManager\UserBundle\Form\Type\UserType
                delete:
                    path:     /{id}/delete
                resetPassword:
                    path:     /{id}/reset-password
            options:
                hidden: true

        group:
            controller: CleverAgeEAVManagerAdminBundle:User
            entity: CleverAge\EAVManager\UserBundle\Entity\Group
            prefix: /groups
            actions:
                list:
                    path:     /
                create:
                    path:     /create
                    form_type: CleverAge\EAVManager\UserBundle\Form\Type\GroupType
                edit:
                    path:     /{id}/edit
                    form_type: CleverAge\EAVManager\UserBundle\Form\Type\GroupType
                delete:
                    path:     /{id}/delete
            options:
                hidden: true

        process:
            controller: CleverAgeEAVManagerAdminBundle:GenericAdmin
            entity: CleverAge\ProcessBundle\Entity\ProcessHistory
            prefix: /process
            actions:
                list:
                    path: /
                show:
                    path: /{id}/show
                delete:
                    path: /{id}/delete
            options:
                icon: history
                hidden: true

        task:
            controller: CleverAgeEAVManagerAdminBundle:GenericAdmin
            entity: CleverAge\ProcessBundle\Entity\TaskHistory
            prefix: /task
            actions:
                list:
                    path: /
                show:
                    path: /{id}/show
                delete:
                    path: /{id}/delete
            options:
                icon: tasks
                hidden: true

        variant:
            controller: CleverAgeEAVManagerAdminBundle:Variant
            entity: '%sidus_data_class%'
            prefix: /variant
            actions:
                select:
                    path:     /{attribute}/{parentId}/select
                    form_type: CleverAge\EAVManager\AdminBundle\Form\Type\VariantFamilySelector
                create:
                    path:     /{attribute}/{parentId}/{familyCode}/create
                    form_type: Sidus\EAVVariantBundle\Form\Type\VariantType
                edit:
                    path:     /{attribute}/{parentId}/{familyCode}/{id}/edit
                    form_type: Sidus\EAVVariantBundle\Form\Type\VariantType
                delete:
                    path:     /{attribute}/{parentId}/{familyCode}/{id}/delete
            options:
                hidden: true
                datagrid: base

        _data:
            controller: CleverAgeEAVManagerAdminBundle:InlineEAVData
            entity: '%sidus_data_class%'
            prefix: /_data
            actions:
                create:
                    path:     /{familyCode}/create
                    form_type: '%eav_form.type%'
                edit:
                    path:     /{familyCode}/{id}/edit
                    form_type: '%eav_form.type%'
                editInline:
                    path:     /{id}/edit
                    form_type: '%eav_form.type%'
                delete:
                    path:     /{familyCode}/{id}/delete
            options:
                hidden: true
