sidus_data_grid:
    configurations:
        user:
            filter_config:
                entity: CleverAgeEAVManagerUserBundle:User
                sortable:
                    - id
                    - createdAt
                    - username
                    - email
                fields:
                    createdAt:
                        type: date_range
                        label: Création
                    email: ~
                    username: ~
            columns:
                id:
                    label: '#'
                username: ~
                email: ~
                lastName:
                    property_path: data.lastName
                firstName:
                    property_path: data.firstName
                printableRoles: ~
                createdAt: ~
                actions:
                    template: CleverAgeEAVManagerAdminBundle:User:partials/list.row.actions.html.twig
            actions:
                create:
                    form_type: CleverAge\EAVManager\AdminBundle\Form\Type\AdminLink
                    label: admin.action.create.label
                    action: create
                    icon: plus
                    attr:
                        class: btn-primary
                        data-target-element: "#tg_right"

        group:
            filter_config:
                entity: CleverAgeEAVManagerUserBundle:Group
                sortable:
                    - id
                    - createdAt
                    - name
                    - roles
                fields:
                    createdAt:
                        type: date_range
                        label: Création
                    name: ~
            columns:
                id:
                    label: '#'
                name: ~
                roles: ~
                createdAt: ~
                actions:
                    template: '%datagrid.actions%'
            actions:
                create:
                    form_type: CleverAge\EAVManager\AdminBundle\Form\Type\AdminLink
                    label: admin.action.create.label
                    action: create
                    icon: plus
                    attr:
                        class: btn-primary
                        data-target-element: "#tg_right"

        resource:
            filter_config:
                entity: CleverAge\EAVManager\AssetBundle\Entity\Document
                sortable:
                    - id
                    - originalFileName
                    - fileSize
                    - mimeType
                    - fileModifiedAt
                default_sort:
                    id: DESC
                fields:
                    originalFileName: ~
                    mimeType:
                        type: choice
                    fileModifiedAt:
                        type: date_range
            columns:
                id:
                    label: '#'
                originalFileName: ~
                type: ~
                fileSize: ~
                mimeType: ~
                fileModifiedAt: ~
                actions:
                    template: CleverAgeEAVManagerAdminBundle:Asset/partials:resource.row.actions.html.twig

        process:
            filter_config:
                entity: CleverAge\ProcessBundle\Entity\ProcessHistory
                sortable:
                    - processCode
                    - startDate
                    - endDate
                    - state
                default_sort:
                    startDate: DESC
                fields:
                    processCode:
                        type: choice
                    startDate:
                        type: date_range
                    endDate:
                        type: date_range
                    state:
                        type: choice
            columns:
                processCode: ~
                startDate: ~
                endDate: ~
                state: ~
                actions:
                    template: CleverAgeEAVManagerAdminBundle:Process/partials:process.row.actions.html.twig

        task:
            filter_config:
                entity: CleverAge\ProcessBundle\Entity\TaskHistory
                results_per_page: 50
                sortable:
                    - taskCode
                    - message
                    - loggedAt
                    - level
                    - reference
                default_sort:
                    loggedAt: DESC
                fields:
#                    processHistory:
#                        type: choice
#                        form_options:
#                            multiple: true
                    taskCode:
                        type: choice
                    message: ~
                    loggedAt:
                        type: date_range
                    level:
                        type: choice
                    reference: ~
            columns:
                processCode:
                    property_path: processHistory.processCode
                taskCode:
                message: ~
                loggedAt: ~
                level: ~
                reference: ~
                context: ~
