sidus_eav_data_grid:
    configurations:
        baseasset:
            family: BaseAsset
            filter_config:
                sortable:
                    - id
                    - createdAt
                    - updatedAt
                fields: []
            columns:
                id:
                    label: '#'
                label:
                    template: '%clickable.template%'
                createdAt: ~
                updatedAt: ~
                actions:
                    template: '%eav_datagrid.actions%'
            actions:
                create:
                    form_type: CleverAge\EAVManager\AdminBundle\Form\Type\AdminLink
                    label: admin.action.create.label
                    action: create
                    icon: plus
                    attr:
                        class: btn-primary
                        data-target-element: '#tg_right'
            reset_button:
                attr:
                    data-target-element: '#tg_center'

        document:
            family: Document
            parent: baseasset
            filter_config:
                sortable:
                    - id
                    - title
                    - mimeType
                    - fileName
                fields:
                    title: ~
                    fileName: ~
                    mimeType:
                        type: choice
            columns:
                id:
                    label: '#'
                title:
                    template: '%clickable.template%'
                fileSize: ~
                mimeType: ~
                fileName: ~
                actions:
                    template: '%eav_datagrid.actions%'

        image:
            family: Image
            parent: baseasset
            filter_config:
                sortable:
                    - id
                    - title
                    - mimeType
                fields:
                    title: ~
                    tags: ~
                    fileName: ~
                    mimeType:
                        type: choice
            columns:
                id:
                    label: '#'
                imageFile:
                    template: CleverAgeEAVManagerAdminBundle:Asset:partials/browse.thumbnail.html.twig
                title:
                    template: '%clickable.template%'
                tags: ~
                mimeType: ~
                filename:
                    property_path: imageFile.originalFilename
                actions:
                    template: '%eav_datagrid.actions%'

        image_browser:
            family: Image
            filter_config:
                results_per_page: 5
                sortable:
                    - id
                    - title
                fields:
                    title: ~
                    tags: ~
            columns:
                id:
                    label: '#'
                imageFile:
                    template: CleverAgeEAVManagerAdminBundle:Asset:partials/browse.thumbnail.html.twig
                title:
                    template: CleverAgeEAVManagerAdminBundle:Asset:partials/browse.row.label.html.twig
                actions:
                    template: CleverAgeEAVManagerAdminBundle:Asset:partials/browse.row.actions.html.twig
            actions:
                create:
                    form_type: CleverAge\EAVManager\AdminBundle\Form\Type\AdminLink
                    label: admin.action.create.label
                    action: create
                    icon: plus
                    attr:
                        class: btn-primary
                        data-target-element: '_CURRENT_MODAL'
            reset_button:
                attr:
                    data-target-element: '_CURRENT_MODAL'

        document_browser:
            family: Document
            filter_config:
                results_per_page: 5
                sortable:
                    - id
                    - title
                fields:
                    title: ~
                    tags: ~
            columns:
                id:
                    label: '#'
                title:
                    template: 'CleverAgeEAVManagerAdminBundle:Asset:browse.row.label.html.twig'
                actions:
                    template: 'CleverAgeEAVManagerAdminBundle:Asset:browse.row.actions.html.twig'
            actions:
                create:
                    form_type: CleverAge\EAVManager\AdminBundle\Form\Type\AdminLink
                    label: admin.action.create.label
                    action: create
                    icon: plus
                    attr:
                        class: btn-primary
                        data-target-element: '_CURRENT_MODAL'
            reset_button:
                attr:
                    data-target-element: '_CURRENT_MODAL'
