# one uploader
oneup_uploader:
    mappings:
        image:
            frontend: blueimp
            allowed_mimetypes: [ image/jpg, image/jpeg, image/png, image/gif ]
            storage:
                type: flysystem
                filesystem: oneup_flysystem.images_filesystem
            max_size: 64000000
        document:
            frontend: blueimp
            storage:
                type: flysystem
                filesystem: oneup_flysystem.documents_filesystem
            max_size: 64000000

oneup_flysystem:
    adapters:
        resources:
            local:
                directory: '%kernel.root_dir%/../var/data/resources'
    filesystems:
        images:
            adapter: resources
        documents:
            adapter: resources

sidus_file_upload:
    configurations:
        image: # must match oneup_uploader mapping key
            entity: CleverAge\EAVManager\AssetBundle\Entity\Image
            filesystem: images
        document:
            entity: CleverAge\EAVManager\AssetBundle\Entity\Document
            filesystem: documents

liip_imagine:
    resolvers:
       default:
          web_path:
            cache_prefix: "images/cache"

    loaders:
        images:
            flysystem:
                filesystem_service: oneup_flysystem.images_filesystem

    filter_sets:
        tiny:
            data_loader: images
            quality: 70
            filters:
                auto_rotate: ~
                thumbnail: { size: [64, 64], mode: outbound }
        thumbnail:
            data_loader: images
            quality: 70
            filters:
                auto_rotate: ~
                thumbnail: { size: [128, 128], mode: outbound }
        small:
            data_loader: images
            quality: 75
            filters:
                thumbnail: { size: [300, 200], mode: outbound }
        preview:
            data_loader: images
            quality: 80
            filters:
                auto_rotate: ~
                thumbnail: { size: [730, 730], mode: inset }
        large:
            data_loader: images
            quality: 90
            filters:
                auto_rotate: ~
                thumbnail: { size: [1900, 1000], mode: inset }
