services:
    eavmanager_admin.attribute_type.document:
        class: '%sidus_eav_model.attribute_type.relation.class%'
        arguments:
            - document
            - documentValue
            - Sidus\FileUploadBundle\Form\Type\ResourceType
            - { resource_type: document }
        tags:
            - { name: sidus.attribute_type }

    eavmanager_admin.attribute_type.image:
        class: '%sidus_eav_model.attribute_type.relation.class%'
        arguments:
            - image
            - imageValue
            - CleverAge\EAVManager\AdminBundle\Form\Type\ImageType
            - { resource_type: image }
        tags:
            - { name: sidus.attribute_type }

    eavmanager_admin.attribute_type.media_browser:
        class: '%sidus_eav_model.attribute_type.eav_relation.class%'
        arguments:
            - media_browser
            - dataValue
            - CleverAge\EAVManager\AssetBundle\Form\Type\MediaBrowserType
        tags:
            - { name: sidus.attribute_type }

    eavmanager_admin.attribute_type.embed_multi_family:
        class: CleverAge\EAVManager\AdminBundle\Model\EmbedMultiFamilyAttributeType
        arguments:
            - embed_multi_family
            - dataValue
            - CleverAge\EAVManager\AdminBundle\Form\Type\EmbedMultiFamilyEntryType
        tags:
            - { name: sidus.attribute_type }
