services:
    eavmanager_eav_model.attribute_type.document:
        class: '%sidus_eav_model.attribute_type.default.class%'
        arguments:
            - document
            - documentValue
            - Sidus\FileUploadBundle\Form\Type\ResourceType
            - { resource_type: document }
        tags:
            - { name: sidus.attribute_type }

    eavmanager_eav_model.attribute_type.image:
        class: '%sidus_eav_model.attribute_type.default.class%'
        arguments:
            - image
            - imageValue
            - CleverAge\EAVManager\AdminBundle\Form\Type\ImageType
            - { resource_type: image }
        tags:
            - { name: sidus.attribute_type }

    eavmanager_eav_model.attribute_type.media_browser:
        class: '%sidus_eav_model.attribute_type.default.class%'
        arguments:
            - media_browser
            - dataValue
            - CleverAge\EAVManager\AssetBundle\Form\Type\MediaBrowserType
        tags:
            - { name: sidus.attribute_type }
